baseURL = "http://lin-h.com/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
title = "LinH's Blog"
theme = "tranquilpeak"
[params]
  dateFormat = "2 January 2006"
  keywords = 'Lin-H,Web Developer,前端,技术分享,程序员,IT,Programmer'
  description = 'Lin-H的个人Blog，记录自己的想法，分享技术、经验。'

name = "Lin-H"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/LICENSE"
homepage = "http://lin-h.com"
tags = ["Lin-H", "Web Developer", "前端", "技术分享", "程序员", "Programmer"]
features = ["blog", "themes", "minimal", "responsive", "fontawesome", "highlight.js"]
min_version = 0.20

[author]
  name = "Lin-H"
  homepage = "http://lin-h.com"

[original]
  name = "Tranquilpeak"
  homepage = "https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak"
  repo = "https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak.git"

[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 1
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 2
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 3
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 4
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
  url = "/#search"
  class = "st-search-show-outputs"
[[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/kakawait"
[[menu.links]]
  weight = 1
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/636472/kakawait"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params.header.rightLink]
  class = "open-algolia-search"
  icon = "search"
  url = "/#search"