# Logo
logo: css/images/logo.png # Empty this to unset logo and show site title in the same place

# Header
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

highlight:
  enable: true

# Contacts
contacts:
  github: http://github.com/Lin-H
  weibo: "http://weibo.com/u/2605326267"
  weibo_name: "7黑林"
  rss: atom.xml

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: useso
# You can choose "useso" instead of "google apis"(default).
# cdn: useso
# OR
# cdn:

# Miscellaneous
google_site_verification:
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
